name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ cs-69.16 ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: README.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: README.md --allow-local-files -o build/README.pdf
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pptx)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: README.md --allow-local-files -o build/README.pptx
        env:
          MARP_USER: root:root

      - name: Check if slides folder exists
        id: slides-folder-exists
        run: bash -c "[[ -d slides ]] ; echo \"has_slides=\$?\" >> \"$GITHUB_OUTPUT\""

      - name: Marp Build (slides folder, if exists)
        if: steps.slides-folder-exists.outputs.has_slides == '0'
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: -I slides/ -o build/slides/
        env:
          MARP_USER: root:root

      - name: Copy images directory (if exists)
        run: if [[ -d slides/img ]]; then cp -R slides/img build/img; fi

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/
